version: '3.8'

# Definiamo i nostri "hard disk esterni"
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Colleghiamo la configurazione
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # Colleghiamo l'hard disk per i dati
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      # Colleghiamo l'hard disk per le dashboard e le impostazioni
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus



