{
 "title": "Sentiment App Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 10, "y": 0 }, "options": { "content": "# MODEL PERFORMANCE\n" } },
  {
   "title": "Sentiment Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentiment_analysis_predictions_total{job=\"fastapi_app\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Sentimet over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "increase(sentiment_analysis_predictions_total{job=\"fastapi_app\"}[5m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 11, "y": 10 }, "options": { "content": "#               API HEALTH" } },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"fastapi_app\"}[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}