name: MLOps CI/CD Pipeline

on:
  # 1. Trigger per i TEST VELOCI (Continuous Integration)
  #    Si attiva a ogni push o pull request sul branch main.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 2. Trigger per il TRAINING PESANTE (Manuale)
  #    Permette di avviare l'intera pipeline manualmente dalla tab "Actions" di GitHub.
  workflow_dispatch:

  # 3. Trigger per il TRAINING PESANTE (Schedulato)
  #    Avvia l'intera pipeline automaticamente una volta a settimana.
  schedule:
    # Esegue ogni Domenica alle 02:00 UTC (formato CRON)
    - cron: '0 2 * * 0'

jobs:
  # --- JOB 1: TEST VELOCI ---
  # Questo job viene eseguito SEMPRE, ad ogni push e pull request.
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -v

  # --- JOB 2: TRAINING E DEPLOY PESANTE ---
  # Questo job viene eseguito SOLO se triggerato manualmente o schedulato,
  # e solo se i test hanno avuto successo.
  train-and-deploy:
    # CONDIZIONE: Esegui questo job solo se il trigger è 'workflow_dispatch' o 'schedule'
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    needs: test # Dipende dal successo del job di test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies for training
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Training and Deploy Script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: python train.py

